Make secondary_http and secondary_redis tests independent
Instead of starting an HTTP or Redis server that lives for the duration
of the test suite, start a new one for each test case. This makes tests
more independent and also opens up for future testing of e.g. different
ports and authentication modes by allowing different server
configurations for each test case.

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -416,6 +416,7 @@ TEST() {
     CURRENT_TEST=$1
     CCACHE_COMPILE="$CCACHE $COMPILER"
 
+    terminate_all_children
     reset_environment
 
     if $verbose; then
@@ -443,7 +444,7 @@ TEST() {
 
 export LC_ALL=C
 
-trap 'terminate_all_children' EXIT # also cleanup after exceptional code flow
+trap terminate_all_children EXIT # also clean up after exceptional code flow
 
 if pwd | grep '[^A-Za-z0-9/.,=_%+-]' >/dev/null 2>&1; then
     cat <<EOF
